apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-reader
rules:
  - apiGroups: [""] # Core API group.
    resources: ["nodes"] # Cluster-scoped resource.
    verbs: ["get", "list"] # Allowed actions on the resource.
