apiVersion: batch/v1
kind: CronJob
metadata:
  name: simple-cronjob
spec:
  schedule: "*/5 * * * *" # This means it runs every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cronjob-container
              image: busybox
              command: ["echo", "Hello from Kubernetes CronJob!"]
          restartPolicy: Never
