apiVersion: batch/v1
kind: Job
metadata:
  name: simple-job
spec:
  # Retry failed pods up to 4 times before marking the Job as failed.
  backoffLimit: 4
  # Abort the Job if it runs longer than 5 seconds.
  activeDeadlineSeconds: 5
  # Require 5 successful pod completions to consider the Job complete.
  completions: 5
  # Run up to 5 pods simultaneously to reach the completions faster.
  parallelism: 5
  # Clean up the Job and its pods 5 seconds after it finishes.
  ttlSecondsAfterFinished: 5
  template:
    spec:
      containers:
        - name: job-container
          image: busybox
          command: ["echo", "Hello from Kubernetes Job!"]
      restartPolicy: Never
