apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: existing-pv-claim
spec:
  accessModes:
    - ReadWriteOnce # ReadOnlyMany ReadWriteMany
  storageClassName: existing-pv
  resources:
    requests:
      storage: 10Gi
