apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: existing-pv-claim
spec:
  accessModes:
    - ReadWriteOnce # ReadOnlyMany ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: existing-pv
