apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota-example
  namespace: your-namespace
spec:
  hard:
    requests.cpu: "10" # Total CPU requests across all pods in the namespace (10 CPUs)
    requests.memory: "20Gi" # Total memory requests across all pods in the namespace (20 GiB)
    limits.cpu: "20" # Total CPU limits across all pods in the namespace (20 CPUs)
    limits.memory: "40Gi" # Total memory limits across all pods in the namespace (40 GiB)
    pods: "50" # Maximum number of pods allowed in the namespace
    services: "10" # Maximum number of services allowed in the namespace
    persistentvolumeclaims: "10" # Maximum number of PersistentVolumeClaims allowed in the namespace
    configmaps: "20" # Maximum number of ConfigMaps allowed in the namespace
    secrets: "20" # Maximum number of Secrets allowed in the namespace
    replicationcontrollers: "10" # Maximum number of ReplicationControllers allowed in the namespace
    resourcequotas: "1" # Maximum number of ResourceQuotas allowed in the namespace
    services.loadbalancers: "2" # Maximum number of services of type LoadBalancer allowed in the namespace
    services.nodeports: "2" # Maximum number of services of type NodePort allowed in the namespace
