apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default # This role applies to the "default" namespace.
  name: pod-reader
rules:
  - apiGroups: [""] # "" indicates the core API group for resources like Pods.
    resources: ["pods"] # Specifies the resource to which permissions are granted (in this case, pods).
    verbs: ["get", "list"] # Allowed actions (verbs) on the resources.
