apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: x
spec:
  replicas: 3
  selector:
    matchLabels:
      x: x
    matchExpressions:
      - key: x
        operator: In # NotIn Exists DoesNotExist
        values:
          - x
  template:
    metadata:
      name: x
    spec:
      containers:
        - name: x
