apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: x
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /app
            pathType: Prefix
            backend:
              service:
                name: x
                port:
                  number: 80
